name: Yupiread
description: "An Modern-Simple Education Gallery And EBook App."
publish_to: 'none'
version: 1.1.10+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  share_plus: ^11.1.0
  file_picker: ^10.3.2
  syncfusion_flutter_pdfviewer: ^30.2.6
  syncfusion_flutter_pdf: ^30.2.6
  docx_to_text: ^1.0.1
  archive: 3.6.1
  xml: ^6.4.2
  path: ^1.8.3
  cunning_document_scanner: ^1.3.1
  permission_handler: ^12.0.0+1
  image_cropper: ^9.1.0
  extended_image: ^10.0.1
  google_mlkit_text_recognition: ^0.15.0
  flutter_quill: ^11.4.2
  flutter_quill_extensions: ^11.0.0-dev.0
  pdf_combiner: ^4.3.8
  pdf: ^3.10.4
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  http: ^1.2.1
  reorderable_grid_view: ^2.2.8
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# Platform support - Android only
platforms:
  android:
    minSdkVersion: 21
    targetSdkVersion: 34
    compileSdkVersion: 34
