name: Yupiread
description: "An Modern-Simple Education Gallery And EBook App."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  file_picker: ^6.1.1
  syncfusion_flutter_pdfviewer: ^24.1.41
  uuid: ^4.2.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
