enum ActivityType {
  photoAdded,
  photoDeleted,
  photoEdited,
  photoViewed,
  photoPageAdded,
  photoPageDeleted,
  photoPageEdited,
  ebookRead,
  ebookCreated,
  ebookAdded,
  ebookCompleted,
  ebookDeleted,
  ebookEdited,
}
